import type { ProductCategory } from '@/types/product';

export const measurementTechnology: ProductCategory = {
  slug: 'measurement-technology',
  title: 'Measurement Technology',
  description:
    'Precision instruments and complete measurement systems for compressed air quality and efficiency monitoring — dew point, flow, leak detection, residual oil, and particle measurement.',
  image: '/images/products/measurement-technology/dewpoint.jpg',
  metaTitle: 'Measurement Technology – Compressed Air Instruments',
  metaDescription:
    'ultrafilter measurement technology: dew point meters, flow meters, leak detection equipment, residual oil analysers, and particle counters for compressed air systems.',
  subcategories: [
    {
      slug: 'dew-point',
      title: 'Dew Point Measurement',
      description: 'Portable and fixed dew point meters for compressed air and technical gas quality verification.',
      image: '/images/products/dew%20point.jpg',
      metaTitle: 'Dew Point Measurement | ultrafilter',
      metaDescription: 'ultrafilter dew point meters for compressed air quality measurement — portable hand-held instruments and fixed-point continuous monitors.',
      heroTitle: 'Dew Point Measurement',
      content: [
        {
          heading: 'Verify Your Dryer Performance',
          body: '<p>Dew point measurement is the primary quality verification method for compressed air drying equipment. ultrafilter dew point meters use capacitive sensor technology to measure the pressure dew point in compressed air and technical gas systems. The range includes portable hand-held instruments for spot checks and fixed transmitters for continuous 24/7 monitoring.</p>',
          specs: [
            { label: 'Measurement range', value: '−100 °C to +20 °C Td' },
            { label: 'Accuracy', value: '± 2 °C Td' },
            { label: 'Response time', value: 'T90 < 60 s (in-flow)' },
            { label: 'Output', value: '4–20 mA / RS485 (Modbus) / display' },
            { label: 'Standards', value: 'ISO 8573-1 Class 1–5 verification' },
          ],
        },
      ],
    },
    {
      slug: 'consumption',
      title: 'Consumption Measurement',
      description: 'Thermal mass flow meters for accurate compressed air consumption measurement and leak quantification.',
      image: '/images/products/flow%20meter.jpg',
      metaTitle: 'Compressed Air Consumption Measurement | ultrafilter',
      metaDescription: 'Thermal mass flow meters for compressed air consumption measurement — no pressure drop, bidirectional measurement, integrated data logging.',
      heroTitle: 'Consumption Measurement',
      content: [
        {
          heading: 'Measure What You Use',
          body: '<p>Understanding compressed air consumption is the first step to reducing energy costs. ultrafilter thermal mass flow meters are inserted directly into the compressed air pipe without process interruption (hot-tap design) and measure mass flow without any pressure drop — providing accurate consumption data even at low flow rates.</p>',
          specs: [
            { label: 'Measurement principle', value: 'Thermal mass flow (calorimetric)' },
            { label: 'Flow range', value: '0.5 – 300 m/s' },
            { label: 'Pipe sizes', value: 'DN 15 – DN 400' },
            { label: 'Output', value: '4–20 mA, pulse, RS485 Modbus' },
            { label: 'Accuracy', value: '± 1.5% of reading' },
          ],
        },
      ],
    },
    {
      slug: 'leak-detection',
      title: 'Leak Detection',
      description: 'Ultrasonic leak detectors for locating compressed air and gas leaks quickly and accurately.',
      image: '/images/products/leak%20detection.jpg',
      metaTitle: 'Compressed Air Leak Detection | ultrafilter',
      metaDescription: 'ultrafilter ultrasonic leak detectors for compressed air and gas leak location — pinpoint leaks in pressurised systems quickly and safely.',
      heroTitle: 'Leak Detection',
      content: [
        {
          heading: 'Find Leaks — Reduce Energy Waste',
          body: '<p>Compressed air leaks are one of the largest sources of energy waste in industrial plants — a typical system loses 20–30% of compressor output through leaks. ultrafilter ultrasonic leak detectors locate leaks quickly by detecting the high-frequency noise generated by escaping gas, even in noisy industrial environments and at distances up to 10 metres.</p>',
          specs: [
            { label: 'Detection principle', value: 'Ultrasonic (40 kHz)' },
            { label: 'Detection distance', value: 'up to 10 m (depending on leak size)' },
            { label: 'Frequency range', value: '20 – 100 kHz' },
            { label: 'Display', value: 'Signal strength bar graph + headphones' },
            { label: 'Standards', value: 'Suitable for ATEX Zone 2 (Ex variants)' },
          ],
        },
      ],
    },
    {
      slug: 'residual-oil',
      title: 'Residual Oil Measurement',
      description: 'Stationary and portable instruments for measuring residual oil content in compressed air.',
      image: '/images/products/residual%20oil.jpg',
      metaTitle: 'Residual Oil Measurement | ultrafilter',
      metaDescription: 'Measure residual oil content in compressed air — stationary monitors and portable analysers for ISO 8573-1 oil class verification.',
      heroTitle: 'Residual Oil Measurement',
      content: [
        {
          heading: 'Verify Oil-Free Air Quality',
          body: '<p>Residual oil in compressed air is invisible and odourless — making measurement essential wherever oil-free air is required. ultrafilter residual oil measurement instruments detect total oil content (aerosol + vapour) in the range of 0.001 to 5 mg/m³, enabling verification of ISO 8573-1 oil classes 1 through 4.</p>',
          specs: [
            { label: 'Measurement range', value: '0.001 – 5 mg/m³ total oil' },
            { label: 'Measurement principle', value: 'Photoionisation (PID)' },
            { label: 'Response time', value: 'T90 < 30 s' },
            { label: 'ISO class verification', value: 'Class 1 to Class 4 (ISO 8573-1)' },
          ],
        },
      ],
    },
    {
      slug: 'particle-measurement',
      title: 'Particle Measurement',
      description: 'Laser particle counters for continuous monitoring of solid particle content in compressed air.',
      image: '/images/products/particle%20counter.jpg',
      metaTitle: 'Particle Measurement in Compressed Air | ultrafilter',
      metaDescription: 'Laser particle counters for 24/7 particle monitoring in compressed air — ISO 8573-1 particle class verification, real-time data logging.',
      heroTitle: 'Particle Measurement',
      content: [
        {
          heading: '24/7 Particle Monitoring',
          body: '<p>ultrafilter laser particle counters provide continuous, real-time measurement of solid particle concentration and size distribution in compressed air. Designed for 24/7 operation, the instruments simultaneously count particles across multiple size channels, enabling ongoing verification of ISO 8573-1 particle class compliance.</p>',
          specs: [
            { label: 'Measurement principle', value: 'Laser light scattering' },
            { label: 'Particle size channels', value: '0.1, 0.5, 1.0, 5.0, 10, 25 µm' },
            { label: 'Operating pressure', value: 'up to 16 bar' },
            { label: 'Output', value: '4–20 mA, RS485 Modbus, USB data logging' },
            { label: 'ISO class', value: 'Particle classes 1–5 (ISO 8573-1)' },
          ],
        },
      ],
    },
    {
      slug: 'displays-data-loggers',
      title: 'Displays / Data Loggers / Software',
      description: 'Central display units, multi-channel data loggers, and analysis software for compressed air monitoring systems.',
      image: '/images/products/display.jpg',
      metaTitle: 'Displays, Data Loggers & Software | ultrafilter',
      metaDescription: 'ultrafilter display units, data loggers, and analysis software for centralising compressed air quality and consumption monitoring data.',
      heroTitle: 'Displays / Data Loggers / Software',
      content: [
        {
          heading: 'Central Monitoring and Data Management',
          body: '<p>ultrafilter display and data logging units bring together measurements from multiple sensors — flow, dew point, pressure, temperature, particle count, residual oil, and power consumption — into a single, clear overview. Data can be logged locally or transmitted to a central SCADA/BMS system via standard industrial interfaces.</p>',
          specs: [
            { label: 'Measured parameters', value: 'Flow, consumption, dew point, pressure, temperature, power, particles, residual oil' },
            { label: 'Interfaces', value: '4–20 mA, RS485 Modbus, Ethernet, USB' },
            { label: 'Display', value: 'Colour TFT touch screen (on multi-channel units)' },
            { label: 'Data logging', value: 'Internal SD card / USB export / cloud (optional)' },
          ],
        },
      ],
    },
    {
      slug: 'calibration',
      title: 'Calibration',
      description: 'Traceable calibration services for dew point, flow, and particle measurement instruments.',
      image: '/images/products/callibration.jpg',
      metaTitle: 'Instrument Calibration Services | ultrafilter',
      metaDescription: 'Traceable calibration of dew point meters, flow meters, and particle counters — DAkkS-accredited calibration laboratory services.',
      heroTitle: 'Calibration Services',
      content: [
        {
          heading: 'Traceable Calibration — Measurement You Can Trust',
          body: '<p>Regular calibration is essential for maintaining measurement accuracy and quality system compliance. ultrafilter offers traceable calibration services for dew point meters, thermal mass flow meters, residual oil analysers, and particle counters — with calibration certificates traceable to national standards.</p>',
          specs: [
            { label: 'Instruments calibrated', value: 'Dew point meters, flow meters, residual oil analysers, particle counters' },
            { label: 'Traceability', value: 'Traceable to national / PTB standards' },
            { label: 'Certificate', value: 'Calibration certificate with uncertainty statement' },
            { label: 'Turnaround', value: 'Typically 5–10 working days' },
          ],
        },
      ],
    },
    {
      slug: 'service',
      title: 'Measurement Service',
      description: 'On-site measurement campaigns, system audits, and ongoing compressed air quality monitoring services.',
      image: '/images/products/measurement-technology/meas-service.jpg',
      metaTitle: 'Measurement Service – On-Site Compressed Air Testing | ultrafilter',
      metaDescription: 'ultrafilter on-site compressed air quality and efficiency measurement services — full system audit reports, ISO 8573-1 compliance testing.',
      heroTitle: 'Measurement Service',
      content: [
        {
          heading: 'On-Site Compressed Air Quality Testing',
          body: '<p>ultrafilter measurement service engineers carry out on-site compressed air quality and efficiency audits using calibrated portable instruments. A full measurement campaign covers dew point, particle count, residual oil, flow rate, and system pressure — delivering a comprehensive ISO 8573-1 compliance report and recommendations for improvement.</p>',
        },
      ],
    },
  ],
};
