import type { NavItem } from '@/types/navigation';

export const navigation: NavItem[] = [
  {
    label: 'Products',
    href: '/products',
    children: [
      {
        label: 'Industrial Filtration',
        href: '/products/industrial-filtration',
        description: 'High-performance filter elements and housings for compressed air and gas treatment.',
        children: [
          { label: 'High-Performance Filter Elements', href: '/products/industrial-filtration/high-performance-filter-elements' },
          { label: 'High-Performance Filters', href: '/products/industrial-filtration/high-performance-filters' },
          { label: 'Replacement Filters', href: '/products/industrial-filtration/replacement-filters' },
        ],
      },
      {
        label: 'Process Filtration',
        href: '/products/process-filtration',
        description: 'Sterile and process filtration solutions for food, beverage, and pharmaceutical industries.',
        children: [
          { label: 'Sterile Filters (P)-SRF', href: '/products/process-filtration/sterile-filters' },
          { label: 'Steam Filters (P)-GS', href: '/products/process-filtration/steam-filters' },
          { label: 'Ventilation Filters', href: '/products/process-filtration/ventilation-filters' },
          { label: 'SM Filters', href: '/products/process-filtration/sm-filters' },
          { label: 'Process Filters', href: '/products/process-filtration/process-filters' },
          { label: 'Industrial as Process', href: '/products/process-filtration/industrial-as-process' },
          { label: 'Process Filter Housings', href: '/products/process-filtration/process-filter-housings' },
          { label: 'Sterile Filter Box P-SLF', href: '/products/process-filtration/sterile-filter-box' },
        ],
      },
      {
        label: 'Drying Technology',
        href: '/products/drying-technology',
        description: 'Compressed air drying solutions from refrigeration to membrane and adsorption dryers.',
        children: [
          { label: 'Refrigeration Dryers', href: '/products/drying-technology/refrigeration-dryers' },
          { label: 'Adsorption Dryers', href: '/products/drying-technology/adsorption-dryers' },
          { label: 'Membrane Dryers', href: '/products/drying-technology/membrane-dryers' },
        ],
      },
      {
        label: 'Condensate Technology',
        href: '/products/condensate-technology',
        description: 'Efficient condensate management — drains, separators, tanks, and coolers.',
        children: [
          { label: 'Condensate Drains', href: '/products/condensate-technology/condensate-drains' },
          { label: 'Oil-Water Separators', href: '/products/condensate-technology/oil-water-separators' },
          { label: 'Compressed Air Tanks', href: '/products/condensate-technology/compressed-air-tanks' },
          { label: 'Cyclone Separators', href: '/products/condensate-technology/cyclone-separators' },
          { label: 'Pre- & After-Coolers', href: '/products/condensate-technology/pre-after-coolers' },
        ],
      },
      {
        label: 'Measurement Technology',
        href: '/products/measurement-technology',
        description: 'Precision instruments for dew point, flow, particle, and residual oil measurement.',
        children: [
          { label: 'Dew Point Measurement', href: '/products/measurement-technology/dew-point' },
          { label: 'Consumption Measurement', href: '/products/measurement-technology/consumption' },
          { label: 'Leak Detection', href: '/products/measurement-technology/leak-detection' },
          { label: 'Residual Oil Measurement', href: '/products/measurement-technology/residual-oil' },
          { label: 'Particle Measurement', href: '/products/measurement-technology/particle-measurement' },
          { label: 'Displays / Data Loggers / Software', href: '/products/measurement-technology/displays-data-loggers' },
          { label: 'Calibration', href: '/products/measurement-technology/calibration' },
          { label: 'Measurement Service', href: '/products/measurement-technology/service' },
        ],
      },
    ],
  },
  {
    label: 'Services',
    href: '/services',
    children: [
      { label: 'Repair Service', href: '/services/repair-service' },
      { label: 'Inspection & Maintenance', href: '/services/inspection-maintenance' },
      { label: 'Full-Service', href: '/services/full-service' },
      { label: 'Energy Audit', href: '/services/energy-audit' },
      { label: 'Quality Measurement & Lab Service', href: '/services/quality-measurement-lab' },
      { label: 'Leak Detection', href: '/services/leak-detection' },
    ],
  },
  {
    label: 'Company',
    href: '/company',
    children: [
      { label: 'About Us', href: '/company/about-us' },
      { label: 'Careers', href: '/company/careers' },
      { label: 'Production', href: '/company/production' },
      { label: 'Research & Development', href: '/company/research-development' },
    ],
  },
];

// Flat list of all routes for sitemap generation
export const allRoutes: string[] = [
  '/',
  '/contact',
  '/downloads',
  '/privacy-policy',
  '/legal-notice',
  '/news',
  '/news/events',
  '/news/articles',
  '/news/newsletter',
  '/news/customer-reviews',
  '/products',
  '/products/industrial-filtration',
  '/products/industrial-filtration/high-performance-filter-elements',
  '/products/industrial-filtration/high-performance-filters',
  '/products/industrial-filtration/replacement-filters',
  '/products/process-filtration',
  '/products/process-filtration/sterile-filters',
  '/products/process-filtration/steam-filters',
  '/products/process-filtration/ventilation-filters',
  '/products/process-filtration/sm-filters',
  '/products/process-filtration/process-filters',
  '/products/process-filtration/industrial-as-process',
  '/products/process-filtration/process-filter-housings',
  '/products/process-filtration/sterile-filter-box',
  '/products/drying-technology',
  '/products/drying-technology/refrigeration-dryers',
  '/products/drying-technology/adsorption-dryers',
  '/products/drying-technology/membrane-dryers',
  '/products/condensate-technology',
  '/products/condensate-technology/condensate-drains',
  '/products/condensate-technology/oil-water-separators',
  '/products/condensate-technology/compressed-air-tanks',
  '/products/condensate-technology/cyclone-separators',
  '/products/condensate-technology/pre-after-coolers',
  '/products/measurement-technology',
  '/products/measurement-technology/dew-point',
  '/products/measurement-technology/consumption',
  '/products/measurement-technology/leak-detection',
  '/products/measurement-technology/residual-oil',
  '/products/measurement-technology/particle-measurement',
  '/products/measurement-technology/displays-data-loggers',
  '/products/measurement-technology/calibration',
  '/products/measurement-technology/service',
  '/services',
  '/services/repair-service',
  '/services/inspection-maintenance',
  '/services/full-service',
  '/services/energy-audit',
  '/services/quality-measurement-lab',
  '/services/leak-detection',
  '/company',
  '/company/about-us',
  '/company/careers',
  '/company/careers/open-positions',
  '/company/production',
  '/company/research-development',
];
