import type { ServicePage } from '@/types/service';

export const services: ServicePage[] = [
  {
    slug: 'repair-service',
    title: 'Repair Service',
    description: 'Professional repair of ultrafilter and third-party filtration and drying equipment using genuine replacement parts.',
    image: '/images/services/services-hero.jpg',
    metaTitle: 'Repair Service | ultrafilter',
    metaDescription: 'ultrafilter repair service — professional repair of filtration, drying, condensate, and measurement equipment. Fast turnaround, genuine parts.',
    heroTitle: 'Repair Service',
    intro: 'Our qualified service engineers repair ultrafilter equipment and selected third-party brands quickly and reliably — using only genuine replacement parts to maintain performance and warranty.',
    blocks: [
      {
        type: 'text',
        heading: 'Fast, Reliable Repairs',
        body: '<p>ultrafilter repair service covers the full product portfolio — filter housings, refrigeration dryers, adsorption dryers, membrane dryers, condensate drains, oil-water separators, and measurement instruments. All repairs are carried out by factory-trained engineers using genuine ultrafilter parts.</p><p>Equipment can be sent to our Hilden workshop or, for larger installations, our engineers can attend on-site. Detailed repair reports are provided with every job.</p>',
      },
      {
        type: 'list',
        heading: 'Repair Services Include',
        items: [
          'Complete overhaul and re-commissioning of refrigeration and adsorption dryers',
          'Filter housing inspection, seal replacement, and pressure testing',
          'Condensate drain repair and function testing',
          'Oil-water separator maintenance and media replacement',
          'Measurement instrument repair, adjustment, and recalibration',
          'Spare parts supply for ultrafilter and selected OEM equipment',
        ],
      },
      {
        type: 'cta',
        heading: 'Request a Repair',
        body: 'Contact our service team to arrange a repair or request a quotation.',
        ctaLabel: 'Contact Us',
        ctaHref: '/contact',
      },
    ],
  },
  {
    slug: 'inspection-maintenance',
    title: 'Inspection & Maintenance',
    description: 'Planned inspection and maintenance agreements to keep your compressed air system running at peak efficiency.',
    image: '/images/services/services-hero.jpg',
    metaTitle: 'Inspection & Maintenance Agreements | ultrafilter',
    metaDescription: 'ultrafilter planned maintenance agreements — scheduled inspection and servicing of your compressed air treatment equipment to prevent unplanned downtime.',
    heroTitle: 'Inspection & Maintenance',
    intro: 'Prevent unplanned downtime with a structured maintenance agreement. ultrafilter service engineers visit at agreed intervals to inspect, service, and document the condition of your compressed air treatment equipment.',
    blocks: [
      {
        type: 'text',
        heading: 'Structured Maintenance — Fewer Surprises',
        body: '<p>A planned maintenance agreement with ultrafilter ensures your filtration, drying, condensate, and measurement equipment is inspected and serviced at manufacturer-recommended intervals. All work is documented in a detailed service report, and any issues found are flagged before they become failures.</p>',
      },
      {
        type: 'list',
        heading: 'Standard Maintenance Scope',
        items: [
          'Filter element inspection and replacement (as required)',
          'Dryer performance check — dew point measurement and refrigerant charge verification',
          'Condensate drain function test and clean',
          'Oil-water separator media inspection and replacement',
          'Measurement instrument check and zero verification',
          'Full written service report with findings and recommendations',
        ],
      },
      {
        type: 'cta',
        heading: 'Request a Maintenance Agreement',
        body: 'Contact our service team to discuss a maintenance schedule tailored to your installation.',
        ctaLabel: 'Contact Us',
        ctaHref: '/contact',
      },
    ],
  },
  {
    slug: 'full-service',
    title: 'Full-Service',
    description: 'Comprehensive full-service packages covering all maintenance, repairs, consumables, and emergency call-outs.',
    image: '/images/services/services-card.jpg',
    metaTitle: 'Full-Service Packages | ultrafilter',
    metaDescription: 'ultrafilter Full-Service — an all-inclusive service package covering planned maintenance, repairs, spare parts, and emergency response for your compressed air system.',
    heroTitle: 'Full-Service',
    intro: 'Transfer full responsibility for your compressed air treatment equipment to ultrafilter. Our Full-Service package covers everything — planned maintenance, unplanned repairs, consumables, spare parts, and 24/7 emergency response.',
    blocks: [
      {
        type: 'text',
        heading: 'Total Peace of Mind',
        body: '<p>The ultrafilter Full-Service package gives you predictable operating costs and the assurance that your compressed air system is always in expert hands. One fixed annual fee covers all planned and unplanned maintenance, genuine spare parts, filter elements, and priority emergency call-out — leaving you free to focus on your core business.</p>',
      },
      {
        type: 'list',
        heading: 'Full-Service Includes',
        items: [
          'All planned inspection and maintenance visits',
          'All unplanned repairs and emergency call-outs',
          'All genuine filter elements and consumables',
          'All spare parts and labour',
          'Priority response within agreed SLA',
          'Detailed service history and documentation',
          'Annual performance report',
        ],
      },
      {
        type: 'cta',
        heading: 'Request a Full-Service Quotation',
        body: 'Contact us to discuss a Full-Service package for your installation.',
        ctaLabel: 'Get in Touch',
        ctaHref: '/contact',
      },
    ],
  },
  {
    slug: 'energy-audit',
    title: 'Energy Audit',
    description: 'Systematic energy audit of your compressed air system to identify savings potential and reduce operating costs.',
    image: '/images/services/services-card.jpg',
    metaTitle: 'Compressed Air Energy Audit | ultrafilter',
    metaDescription: 'ultrafilter compressed air energy audit — measure consumption, identify leaks, assess system efficiency, and receive a detailed savings roadmap.',
    heroTitle: 'Energy Audit',
    intro: 'Compressed air is one of the most expensive utilities in industrial production. A systematic ultrafilter Energy Audit identifies exactly where energy is being wasted and provides a clear roadmap for cost reduction.',
    blocks: [
      {
        type: 'text',
        heading: 'Where Is Your Energy Going?',
        body: '<p>In a typical compressed air system, 20–30% of compressor output is lost through leaks, 10–15% is wasted through inappropriate pressure levels, and further losses occur through inefficient filtration and drying equipment. An ultrafilter Energy Audit measures all of these parameters on-site and delivers a detailed report quantifying energy waste and the investment required to eliminate it.</p>',
      },
      {
        type: 'list',
        heading: 'Energy Audit Scope',
        items: [
          'Full system pressure mapping and flow measurement',
          'Compressor performance and load profile analysis',
          'Leak detection survey with quantified leak rate measurement',
          'Filtration and drying equipment efficiency assessment',
          'Condensate system review',
          'Detailed audit report with ROI calculations for each recommendation',
          'Follow-up support for implementation',
        ],
      },
      {
        type: 'cta',
        heading: 'Book an Energy Audit',
        body: 'Contact us to arrange an on-site energy audit for your compressed air system.',
        ctaLabel: 'Book Now',
        ctaHref: '/contact',
      },
    ],
  },
  {
    slug: 'quality-measurement-lab',
    title: 'Quality Measurement & Lab Service',
    description: 'On-site compressed air quality measurement and laboratory analysis services for ISO 8573-1 compliance verification.',
    image: '/images/services/services-card.jpg',
    metaTitle: 'Quality Measurement & Lab Service | ultrafilter',
    metaDescription: 'ultrafilter quality measurement and laboratory services — ISO 8573-1 compliance testing, on-site measurement, and laboratory analysis of compressed air quality.',
    heroTitle: 'Quality Measurement & Lab Service',
    intro: 'Demonstrate compliance with compressed air quality standards through independent measurement and laboratory analysis — carried out by ultrafilter measurement specialists using calibrated instruments and accredited laboratory methods.',
    blocks: [
      {
        type: 'text',
        heading: 'ISO 8573-1 Compliance Testing',
        body: '<p>Many industries are required to demonstrate that compressed air used in production meets defined quality standards (ISO 8573-1, pharmacopeial standards, food safety regulations). ultrafilter provides a complete measurement and laboratory service covering all relevant parameters — particles, water content (dew point), and total oil content — delivering a traceable compliance test report.</p>',
      },
      {
        type: 'list',
        heading: 'Services Offered',
        items: [
          'On-site dew point measurement (ISO 8573-1 moisture classes)',
          'On-site particle count measurement (ISO 8573-1 particle classes 1–5)',
          'On-site residual oil measurement (ISO 8573-1 oil classes 1–4)',
          'Laboratory analysis of oil content by GC-MS method',
          'Microbiological testing of compressed air (CFU counts)',
          'Full ISO 8573-1 compliance test report with certificate',
        ],
      },
      {
        type: 'cta',
        heading: 'Request a Quality Measurement',
        body: 'Contact our laboratory team to arrange on-site or laboratory testing.',
        ctaLabel: 'Contact the Lab',
        ctaHref: '/contact',
      },
    ],
  },
  {
    slug: 'leak-detection',
    title: 'Leak Detection Service',
    description: 'Professional on-site compressed air and gas leak detection survey using ultrasonic equipment.',
    image: '/images/services/services-card.jpg',
    metaTitle: 'Leak Detection Service | ultrafilter',
    metaDescription: 'ultrafilter on-site leak detection service — ultrasonic leak survey of your compressed air system, quantified leak report, and repair recommendations.',
    heroTitle: 'Leak Detection Service',
    intro: 'A single compressed air leak survey from ultrafilter can identify tens of thousands of euros in annual energy savings. Our engineers survey your entire compressed air distribution system using ultrasonic equipment and deliver a prioritised leak report.',
    blocks: [
      {
        type: 'text',
        heading: 'Locate, Quantify, and Eliminate Leaks',
        body: '<p>ultrafilter leak detection engineers use professional-grade ultrasonic instruments to locate every leak in your compressed air distribution system — from compressor room to point-of-use. Each leak is photographed, GPS-tagged, and quantified (in m³/h and annual energy cost). You receive a complete leak survey report with prioritised repair recommendations and a calculation of potential annual savings.</p>',
      },
      {
        type: 'list',
        heading: 'Leak Detection Service Includes',
        items: [
          'Complete system survey using ultrasonic leak detection equipment',
          'Identification and tagging of all leaks found',
          'Quantification of leak rate (m³/h) and annual energy cost per leak',
          'Photographic documentation of each leak location',
          'Full leak survey report with prioritised repair list',
          'Calculation of total potential annual energy savings',
          'Optional follow-up verification survey after repairs',
        ],
      },
      {
        type: 'cta',
        heading: 'Book a Leak Detection Survey',
        body: 'Contact us to arrange a leak detection survey for your site.',
        ctaLabel: 'Book a Survey',
        ctaHref: '/contact',
      },
    ],
  },
];
